export const readmeSections = [
    {
      item: "Title and description",
      usage: "# Project Title\n\nA brief description of what this project does and who it's for",
      description: "This section is the title and description of the project. It is the first section of the readme file. It is the title of the project and a brief description of what it does and who it's for.",
      emoji: "📄",
      useCases: ["project", "portfolio"],
    },
    {
      item: "Acknowledgements",
      usage: "## Acknowledgements\n\n- [Awesome Readme Templates](https://awesomeopensource.com/project/elangosundar/awesome-README-templates)",
      description: "This section is the acknowledgements section of the project. It is the section that acknowledges the people who helped you create this project.",
      emoji: "🙏",
      useCases: ["project"],
    },
    {
      item: "API Reference",
      usage: "## API Reference\n\n#### Get all items\n\n```http\n  GET /api/items\n```\n\n| Parameter | Type     | Description                |\n| :-------- | :------- | :------------------------- |\n| `api_key` | `string` | **Required**. Your API key |",
      description: "This section is the API reference section of the project. It is the section that provides a reference to the API of the project.",
      emoji: "📄",
      useCases: ["project", "library"],
    },
    {
      item: "Appendix",
      usage: "## Appendix\n\n- [Appendix](https://example.com/appendix)",
      description: "This section is the appendix section of the project. It is the section that provides additional information about the project.",
      emoji: "📄",
      useCases: ["project"],
    },
    {
      item: "Authors",
      usage: "## Authors\n\n- [Author Name](https://example.com/author)",
      description: "This section is the authors section of the project. It is the section that provides the authors of the project.",
      emoji: "📄",
      useCases: ["project", "portfolio"],
    },
    {
      item: "Badges",
      usage: `## Badges 📄\n\n- [![MIT License](https://img.shields.io/badge/License-MIT-green.svg)](https://opensource.org/licenses/MIT)\n- [![GitHub Stars](https://img.shields.io/github/stars/username/repository.svg)](https://github.com/username/repository/stargazers)\n- [![Build Status](https://img.shields.io/badge/build-passing-brightgreen)](https://example.com/build-status)\n`,
      description: "This section provides badges related to the project, such as licenses, build status, or GitHub stats. Add badges from resources like: [shields.io](https://shields.io/).",
      emoji: "🏅",
      useCases: ["project", "library"],
    },    
    {
      item: "Color Reference",
      usage: "## Color Reference\n\n| Color | Hex | RGB |\n| :---- | :---- | :---- |\n| Primary | #000000 | 0, 0, 0 |\n| Secondary | #FFFFFF | 255, 255, 255 |",
      description: "This section is the color reference section of the project. It is the section that provides the color reference of the project.",
      emoji: "🎨",
      useCases: ["project"],
    },
    {
      item: "Contributing",
      usage: "## Contributing\n\n- [Contributing](https://example.com/contributing) Contributions are always welcome! See `contributing.md` for ways to get started.",
      description: "This section is the contributing section of the project. It is the section that provides the contributing guidelines of the project.",
      emoji: "🤝",
      useCases: ["project", "library"],
    },
    {
      item: "Demo",
      usage: "## Demo\n\n- [Demo](https://example.com/demo) Insert gif or link to demo",
      description: "This section is the demo section of the project. It is the section that provides the demo of the project.",
      emoji: "🎥",
      useCases: ["project", "portfolio"],
    },
    {
      item: "Deployment",
      usage: "## Deployment\n\n- [Deployment](https://example.com/deployment) Insert steps to deploy the project like",
      description: "This section is the deployment section of the project. It is the section that provides the deployment instructions of the project.",
      emoji: "🚀",
      useCases: ["project"],
    },
    {
      item: "Documentation",
      usage: "## Documentation\n\n- [Documentation](https://example.com/documentation) Insert steps to document the project like",
      description: "This section is the documentation section of the project. It is the section that provides the documentation of the project.",
      emoji: "📚",
      useCases: ["project", "library"],
    },
    {
      item: "Environment Variables",
      usage: "## Environment Variables\n\nTo run this project, you will need to add the following environment variables to your .env file `API_KEY=your_api_key`",
      description: "This section is the environment variables section of the project. It is the section that provides the environment variables of the project.",
      emoji: "🔑",
      useCases: ["project"],
    },
    {
      item: "FAQ",
      usage: "## FAQ\n\n#### What is this project?",
      description: "This section is the FAQ section of the project. It is the section that provides the FAQ of the project.",
      emoji: "❓",
      useCases: ["project", "portfolio"],
    },
    {
      item: "Features",
      usage: "## Features\n\n- Feature 1\n- Feature 2",
      description: "This section is the features section of the project. It is the section that provides the features of the project.",
      emoji: "✨",
      useCases: ["project", "portfolio"],
    },
    {
      item: "Installation",
      usage: "## Installation\n\n- [Installation](https://example.com/installation) \n Insert steps to install the project like ```bash\n  git clone https://github.com/username/repository.git\n  cd repository\n  npm install\n  npm run build\n  npm run start\n```",
      description: "This section is the installation section of the project. It is the section that provides the installation instructions of the project.",
      emoji: "💻",
      useCases: ["project"],
    },
    {
      item: "Github Profile - About Me",
      usage: "## About Me\n\n- I'm a Fullstack Developer with a passion for building scalable and efficient web applications.",
      description: "This section is the about me section of the project. It is the section that provides the about me of the project.",
      emoji: "👤",
      useCases: ["portfolio"],
    },
  ];
  